console.log("Q1");
console.log("Hello JavaScript");
console.log("Q2");
console.log("Hirdesh , 24 and shahjahanpur ");
console.log("Q3");
console.warn("This is a warning message");
console.log("Q4");
console.error("This is an error message");
console.log("Q5");
console.table({ name: "Hirdesh", age: 24, city: "Shahjahanpur" });

console.log("### Variables");
console.log("Q1");
let studentName = "Hirdesh";
console.log("Q2");
let age = 24;
console.log(studentName, age);
console.log("Q3");
let a = 10;
let b = 20;
let c = a;
a = b;
b = c;
console.log(a, b);
console.log("Q4");
const pi = 3.14;
console.log(pi);
console.log("Q5");
let z;
console.log(z);
console.log("Q6");
let score = 10;
score += 10;
console.log(score);
console.log("### Type Conversion & Coercion");
console.log("Q1");
let num1 = "10";
num1 = Number(num1);
console.log(num1);
console.log("Q2");
let num2 = 20;
num2 = String(num2);
console.log(num2);
console.log("Q3");
let num3 = "true";
num3 = Boolean(num3);
console.log(num3);
console.log("Q4");
console.log("5" + 2);
console.log("5" - 2);
console.log(true + 1);
console.log("Q1");
a = "123abc";
a = Number(a);
console.log(a);
console.log("Q2");
console.log(parseInt("500px"));
console.log("### Conditionals");
console.log("Q1");
